---
##################################
# YourPlugin Made By TheDeibo :D #
##################################

# PLUGIN COMMAND - Command has to be lower case AND no special characters
Command: "test"

# PLUGIN NAME - SHORT AND SIMPLE 
Name: "Example"

# PLUGIN IT'S SELF
Slot1: "Ejemplo"
Slot2: "Ejemplo"
Slot3: "Ejemplo"
Slot4: "Ejemplo"
Slot5: "Ejemplo"
Slot6: "Ejemplo"

# DO NOT ADD MORE COMMANDS, NAMES, 
# OR ADD SLOTS TO THE CONGIG, BECAUSE
# IT MAY CORRUPT THE COFIG 
...
